const productsList = [
    {
      id: 0,
      name: "SYOSS Ceramide Complex",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "Lakier do wlosow",
      price: 22.99,
      image: "./images/lakier1.png",
    },
    {
      id: 1,
      name: "WELLA WELLAFLEX Instant Volume Boost",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "Lakier do wlosow",
      price: 14.49,
      image: "./images/lakier2.png",
    },
    {
      id: 2,
      name: "SCHWARZKOPF TAFT Power & Fullness",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "Lakier do wlosow",
      price: 17.99,
      image: "./images/lakier3.png",
      sale: true,
      saleAmount: 4,
    },
    {
      id: 3,
      name: "JOOP!",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "Perfumy",
      price: 224.99,
      image: "./images/perfumy1.png",
    },
    {
      id: 4,
      name: "ARTISCENT Santal Frais",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "Perfumy",
      price: 49.99,
      image: "./images/perfumy2.png",
    },
    {
      id: 5,
      name: "DAVID BECKHAM Amber Breeze",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "Perfumy",
      price: 134.99,
      image: "./images/perfumy3.png",
      sale: true,
      saleAmount: 45,
    },
    {
      id: 6,
      name: "MASVERI Men",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "Szampon",
      price: 28.49,
      image: "./images/szampon1.png",
    },
    {
      id: 7,
      name: "DOVE BABY",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "Szampon",
      price: 29.99,
      image: "./images/szampon2.png",
    },
    {
      id: 8,
      name: "SCHWARZKOPF PALETTE Color Shampoo",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "Szampon",
      price: 19.99,
      image: "./images/szampon3.png",
    },
  ];